## tmp loading data

In [50]:
import pandas as pd
#data_exp = pd.read_excel('sheet_full_environment_experiments.xlsx', sheet_name='default')
data_exp = pd.read_csv('sheet_full_environment_experiments.csv')

data_exp

,Area,Reward,Environment Type,Algorithm,Episodes,Max Sumo Steps,Traffic Scale,Seed,Runned By,Reward of Last Episode,...,Derivative of Reward,Waiting Time,Speed,Depart Delay,Time Loss,Waiting Car,Total Time,Device,Notes,Study Group
0,Area2 (Mosheer Ismail),Literature,GroupedSumoEnv,D3QN,200,2000,0٫14,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Area2 (Mosheer Ismail),Literature,GroupedSumoEnv,D3QN,200,2000,0٫14,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Area2 (Mosheer Ismail),Literature,GroupedSumoEnv,D3QN,200,2000,0٫14,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Area2 (Mosheer Ismail),Literature,GroupedSumoEnv,D3QN,200,2000,0٫14,3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Area2 (Mosheer Ismail),Literature,GroupedSumoEnv,D3QN,200,2000,0٫14,mean,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1437,Area3 (San Stefano),Proposed,HighGroupedSumoEnv,PPO,1000,4000,0٫38,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1438,Area3 (San Stefano),Proposed,HighGroupedSumoEnv,PPO,1000,4000,0٫38,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1439,Area3 (San Stefano),Proposed,HighGroupedSumoEnv,PPO,1000,4000,0٫38,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1440,Area3 (San Stefano),Proposed,HighGroupedSumoEnv,PPO,1000,4000,0٫38,3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1441,Area3 (San Stefano),Proposed,HighGroupedSumoEnv,PPO,1000,4000,0٫38,mean,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
# select one done experiments
data_exp[data_exp['Study Group'].str.contains('Max Sumo Steps Effect;', na=False)]

,Area,Reward,Environment Type,Algorithm,Episodes,Max Sumo Steps,Traffic Scale,Seed,Runned By,Reward of Last Episode,...,Derivative of Reward,Waiting Time,Speed,Depart Delay,Time Loss,Waiting Car,Total Time,Device,Notes,Study Group
577,Area2 (Mosheer Ismail),Proposed,HighGroupedSumoEnv,D3QN,350,2000,0٫38,0,Ahmed,-13.4,...,6.994227010584536,63.44,8.13,394.56,95.38,2366.0,24.952,NaN,NaN,Algorithm Performance; Episode Effect; Max Sum...
587,Area2 (Mosheer Ismail),Proposed,HighGroupedSumoEnv,D3QN,350,1500,0٫38,0,Marwa,-13.559,...,0.9645585018107443,60.16,8.23,296.89,90.31,1717.0,12.266,i5,NaN,Max Sumo Steps Effect;
597,Area2 (Mosheer Ismail),Proposed,HighGroupedSumoEnv,D3QN,350,4000,0٫38,0,Marwa,-28.92,...,10.347762650608985,69.34,8.28,778.09,102.61,4801.0,25.257,i5,NaN,Max Sumo Steps Effect;
667,Area2 (Mosheer Ismail),Proposed,HighGroupedSumoEnv,PPO,350,2000,0٫38,0,Mostafa,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Algorithm Performance; Episode Effect; Max Sum...
677,Area2 (Mosheer Ismail),Proposed,HighGroupedSumoEnv,PPO,350,1500,0٫38,0,Rimon,-13.053000450134277,...,3.351461410522461,63.21,8.15,271.6,94.56,1736.0,12.28,colab,NaN,Max Sumo Steps Effect;
687,Area2 (Mosheer Ismail),Proposed,HighGroupedSumoEnv,PPO,350,4000,0٫38,0,Rimon,-38.284000396728516,...,9.48275375366211,66.02,08.06,786.73,99.45,4774.0,19.734,colab,NaN,Max Sumo Steps Effect;
1297,Area3 (San Stefano),Proposed,HighGroupedSumoEnv,D3QN,350,2000,0٫38,0,Bichay,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Algorithm Performance; Episode Effect; Max Sum...
1307,Area3 (San Stefano),Proposed,HighGroupedSumoEnv,D3QN,350,1500,0٫38,0,Marwa,22.153,...,4.194350148485022,23.92,26.3,521.85,108.51,1692.0,16.565,i5,NaN,Max Sumo Steps Effect;
1317,Area3 (San Stefano),Proposed,HighGroupedSumoEnv,D3QN,350,4000,0٫38,0,Marwa,63.608,...,15.187459959647946,25.32,25.2,1502.39,114.49,4710.0,41.979,i5,NaN,Max Sumo Steps Effect;
1387,Area3 (San Stefano),Proposed,HighGroupedSumoEnv,PPO,350,2000,0٫38,0,Taha,28.348,...,6.29,25.57,24.89,716.4,113.46,2274.0,15.912,colab,NaN,Algorithm Performance; Episode Effect; Max Sum...
1397,Area3 (San Stefano),Proposed,HighGroupedSumoEnv,PPO,350,1500,0٫38,0,Taha,24.238,...,7.87,24.32,25.9,519.88,108.44,1693.0,13.255,colab,NaN,Max Sumo Steps Effect;
1407,Area3 (San Stefano),Proposed,HighGroupedSumoEnv,PPO,350,4000,0٫38,0,Taha,49.6,...,6.27,31.79,25.14,1497.18,121.3,4708.0,21.915,colab,results after evaluating --strange reward on e...,Max Sumo Steps Effect;

area2 - 1000 time - 350 eps
2 alg * 2 re * 2 lev * 2 scale * 4 se

In [53]:
data_exp.columns

Index(['Area', 'Reward', 'Environment Type', 'Algorithm', 'Episodes',
       'Max Sumo Steps', 'Traffic Scale', 'Seed', 'Runned By',
       'Reward of Last Episode', 'Average Reward for Evaluated Episodes',
       'Derivative of Reward', 'Waiting Time', 'Speed', 'Depart Delay',
       'Time Loss', 'Waiting Car', 'Total Time', 'Device', 'Notes',
       'Study Group'],
      dtype='object')

In [54]:
# Write new experiments
data_new_2000 = data_exp[(data_exp['Area']=='Area2 (Mosheer Ismail)') & (data_exp['Episodes']==350) & (data_exp['Max Sumo Steps']==2000)& (data_exp['Seed']!='mean')]
data_new_2000

,Area,Reward,Environment Type,Algorithm,Episodes,Max Sumo Steps,Traffic Scale,Seed,Runned By,Reward of Last Episode,...,Derivative of Reward,Waiting Time,Speed,Depart Delay,Time Loss,Waiting Car,Total Time,Device,Notes,Study Group
30,Area2 (Mosheer Ismail),Literature,GroupedSumoEnv,D3QN,350,2000,0٫14,0,Rimon,-37.453,...,58.640624999999986,82.96,9.29,154.15,122.71,565.0,40.175,colab,NaN,NaN
31,Area2 (Mosheer Ismail),Literature,GroupedSumoEnv,D3QN,350,2000,0٫14,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Area2 (Mosheer Ismail),Literature,GroupedSumoEnv,D3QN,350,2000,0٫14,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Area2 (Mosheer Ismail),Literature,GroupedSumoEnv,D3QN,350,2000,0٫14,3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Area2 (Mosheer Ismail),Literature,GroupedSumoEnv,D3QN,350,2000,0٫38,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
665,Area2 (Mosheer Ismail),Proposed,HighGroupedSumoEnv,PPO,350,2000,0٫14,3,Mostafa,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Algorithm Performance;
667,Area2 (Mosheer Ismail),Proposed,HighGroupedSumoEnv,PPO,350,2000,0٫38,0,Mostafa,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Algorithm Performance; Episode Effect; Max Sum...
668,Area2 (Mosheer Ismail),Proposed,HighGroupedSumoEnv,PPO,350,2000,0٫38,1,Mostafa,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Algorithm Performance;
669,Area2 (Mosheer Ismail),Proposed,HighGroupedSumoEnv,PPO,350,2000,0٫38,2,Mostafa,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Algorithm Performance;
670,Area2 (Mosheer Ismail),Proposed,HighGroupedSumoEnv,PPO,350,2000,0٫38,3,Rimon,-21.531999588012695,...,0.10833549499511719,64.91,8.0,390.14,97.24,2373.0,12.358,colab,NaN,Algorithm Performance;

In [55]:
mask = (
    #(data_exp['Area'] == 'Area2 (Mosheer Ismail)') &
    (data_exp['Episodes'] == 350) &
    (data_exp['Max Sumo Steps'] == 2000) &
    (data_exp['Seed'] != 'mean')
)
len(mask==False)

1442

In [56]:
data_exp['Area'].values

array(['Area2 (Mosheer Ismail)', 'Area2 (Mosheer Ismail)',
       'Area2 (Mosheer Ismail)', ..., 'Area3 (San Stefano)',
       'Area3 (San Stefano)', 'Area3 (San Stefano)'], dtype=object)

In [58]:
len(data_exp[mask & (data_exp['Study Group'].isna())])

88

In [59]:
data_exp.loc[ (mask & (data_exp['Study Group'].isna()))]

,Area,Reward,Environment Type,Algorithm,Episodes,Max Sumo Steps,Traffic Scale,Seed,Runned By,Reward of Last Episode,...,Derivative of Reward,Waiting Time,Speed,Depart Delay,Time Loss,Waiting Car,Total Time,Device,Notes,Study Group
30,Area2 (Mosheer Ismail),Literature,GroupedSumoEnv,D3QN,350,2000,0٫14,0,Rimon,-37.453,...,58.640624999999986,82.96,9.29,154.15,122.71,565.0,40.175,colab,NaN,NaN
31,Area2 (Mosheer Ismail),Literature,GroupedSumoEnv,D3QN,350,2000,0٫14,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Area2 (Mosheer Ismail),Literature,GroupedSumoEnv,D3QN,350,2000,0٫14,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Area2 (Mosheer Ismail),Literature,GroupedSumoEnv,D3QN,350,2000,0٫14,3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Area2 (Mosheer Ismail),Literature,GroupedSumoEnv,D3QN,350,2000,0٫38,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1204,Area3 (San Stefano),Proposed,GroupedSumoEnv,PPO,350,2000,0٫14,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1205,Area3 (San Stefano),Proposed,GroupedSumoEnv,PPO,350,2000,0٫14,3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1208,Area3 (San Stefano),Proposed,GroupedSumoEnv,PPO,350,2000,0٫38,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1209,Area3 (San Stefano),Proposed,GroupedSumoEnv,PPO,350,2000,0٫38,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1210,Area3 (San Stefano),Proposed,GroupedSumoEnv,PPO,350,2000,0٫38,3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
data_exp.loc[ (mask & (data_exp['Study Group'].isna())), 'Study Group'] = "Exp2"

In [ ]:
#data_exp[mask].to_csv('tmp.csv')

In [61]:
data_exp.to_excel('sheet_full_environment_experiments_1.xlsx', index=False)

# Processing on comparable experiments

## Helper function

In [33]:
import datetime
def clean_datatime(value):
        if isinstance(value, datetime.datetime):          
            return value.month + value.day * 0.01
        elif isinstance(value, str):
            return float(value.replace('٫', '.'))
            #return float(value)
        else:
            return value
        
def clean_columns_datatime(data):
    for column in numeric_target_columns:#['Seeds', 'Total Reward', 'Waiting', 'Speed','Depart Delay', 'Time Loss', 'Waiting Car', 'Total Time(m)']:
        if column in data.columns:
            data.loc[:, column] = data[column].apply(lambda x: clean_datatime(x))
    return data

def get_grouped_seed(data): ## seeds are after each other on same experiments
    df = data.reset_index(drop=True)
    result_rows = []
    i = 0

    while i < len(df) - 2:
        group = df.iloc[i:i+3]
        if set(group['Seed']) == {0, 1, 2}:  # Check if Seeds are 0, 1, 2
            # Average numeric columns
            numeric_cols = group.select_dtypes(include='number').columns
            avg_numeric = group[numeric_cols].mean()
            
            # Keep non-numeric columns from the first row
            non_numeric_cols = group.select_dtypes(exclude='number').columns
            non_numeric = group.iloc[0][non_numeric_cols]
            
            # Combine into a single averaged row
            new_row = pd.concat([non_numeric, avg_numeric])
            result_rows.append(new_row)
            
            i += 3  # Skip the group of 3 rows
        else:
            result_rows.append(df.iloc[i])  # Add this row as is
            i += 1

    # Add any remaining rows that were not part of a group
    while i < len(df):
        result_rows.append(df.iloc[i])
        i += 1

    # Create the final DataFrame
    result_df = pd.DataFrame(result_rows)

    # Now result_df contains the modified DataFrame with averaged rows
    return result_df

In [ ]:
def prepare_data_benechmark(data):
    '''
    returns data,data_groubed_Seed
    '''
    #clean numeric datatime
    data = clean_columns_datatime(data)

    # makedata groubed on seed
    data_groubed_Seed = get_grouped_seed(data)
    return data,data_groubed_Seed

In [92]:
import matplotlib.pyplot as plt
def plot_data_around_seed(data,data_groubed,column_x,column_y, title='',label='',marker='--',color='blue'):
    
    for i in range(3):
        plt.plot(data[data['Seed']==i][column_x],data[data['Seed']==i][column_y], label =f'seed {i} with {label}',linestyle=marker,alpha=.7,linewidth=1.5)
        #print(f"Plotting seed {i} for {column_y}, length={len(data[data['Seeds']==i])}")

    plt.plot(data_groubed[column_x],data_groubed[column_y],label ='average'+label,linestyle='-',color=color,linewidth=2.5)
    plt.title(title)
    plt.xlabel(column_x)
    plt.ylabel(column_y)

## Code

In [ ]:
import pandas as pd
#data_exp = pd.read_excel('sheet_full_environment_experiments.xlsx', sheet_name='default')
data_exp = pd.read_excel('full_exp2.xlsx', sheet_name='sheet1')

data_exp

In [15]:
numeric_target_columns = ['Episodes','Max Sumo Steps(s)', 'Traffic Scale', 'Seed',
       'Reward of Last Episode', 'Average Reward for Evaluated Episodes',
       'Derivative of Reward', 'Waiting Time (s)', 'Speed (m/s)',
       'Depart Delay (s)', 'Time Loss (s)', 'Waiting Car', 'Total Time (M)',
       ]

In [94]:
set(data_exp['Study Group'].values)

{'Algorithm Performance;',
 'Algorithm Performance; Episode Effect; Max Sumo Steps Effect; Reward Function Effect; Environment Type Effect;',
 'Environment Type Effect;',
 'Episode Effect;',
 'Exp2',
 'Max Sumo Steps Effect;',
 'Reward Function Effect;',
 nan}

In [ ]:
data_exp_episode_effect = data_exp[data_exp['Study Group'].str.contains('Episode Effect;', na=False)]

data_exp_episode_effect

In [147]:
data_exp.columns

Index(['Area', 'Reward', 'Environment Type', 'Algorithm', 'Episodes',
       'Max Sumo Steps(s)', 'Traffic Scale', 'Seed', 'Runned By',
       'Reward of Last Episode', 'Average Reward for Evaluated Episodes',
       'Derivative of Reward', 'Waiting Time (s)', 'Speed (m/s)',
       'Depart Delay (s)', 'Time Loss (s)', 'Waiting Car', 'Total Time (M)',
       'Device', 'Notes', 'Study Group'],
      dtype='object')

In [148]:
data_exp['Area'].values

array(['Area2 (Mosheer Ismail)', 'Area2 (Mosheer Ismail)',
       'Area2 (Mosheer Ismail)', ..., 'Area3 (San Stefano)',
       'Area3 (San Stefano)', 'Area3 (San Stefano)'], dtype=object)

In [ ]:
column_x ='Episodes'
numeric_target_columns = ['Reward of Last Episode', 'Average Reward for Evaluated Episodes','Waiting Time (s)','Speed (m/s)','Depart Delay (s)', 'Time Loss (s)', 'Waiting Car', 'Total Time (M)']

In [ ]:
import matplotlib.pyplot as plt

# Unique combinations
areas = data_exp_episode_effect['Area'].unique()
algorithms = data_exp_episode_effect['Algorithm'].unique()
combinations = [(a, alg) for a in areas for alg in algorithms]

# Layout control
n_cols = 2  # or 3 if you prefer
n_rows = len(combinations) * len(numeric_target_columns) // n_cols + 1

fig, axes = plt.subplots(n_rows, n_cols, figsize=(7 * n_cols, 4.5 * n_rows), squeeze=False)

# Flatten axes array for easier indexing
axes = axes.flatten()

plot_idx = 0
for area, algorithm in combinations:
    # Filter data
    filtered = data_exp_episode_effect[
        (data_exp_episode_effect['Area'] == area) &
        (data_exp_episode_effect['Algorithm'] == algorithm)
    ]

    if filtered.empty:
        continue

    data, data_groubed = prepare_data_benechmark(filtered)

    for column_y in numeric_target_columns:
        if plot_idx >= len(axes):
            break  # safety

        ax = axes[plot_idx]

        # Plot each seed line
        for seed in [0, 1, 2]:
            subset = data[data['Seed'] == seed]
            if column_x in subset.columns and column_y in subset.columns:
                ax.plot(subset[column_x], subset[column_y], label=f'Seed {seed}', linestyle='--', alpha=0.7)

        # Plot average line
        if column_x in data_groubed.columns and column_y in data_groubed.columns:
            ax.plot(data_groubed[column_x], data_groubed[column_y], label='Avg', linestyle='-', color='blue', linewidth=2.5)

        # Title and labels with adjusted font sizes
        ax.set_title(f'{area} | {algorithm} | {column_y}', fontsize=12)
        ax.set_xlabel(column_x, fontsize=10)
        ax.set_ylabel(column_y, fontsize=10)
        ax.legend(fontsize=9)

        plot_idx += 1

# Hide any unused subplots
for i in range(plot_idx, len(axes)):
    fig.delaxes(axes[i])

plt.tight_layout()
plt.show()

## Anova

In [152]:
import pandas as pd
from scipy.stats import ttest_ind, f_oneway

def simple_stat_test(df, metric, group_col):
    groups = df[group_col].unique() ##note should each group have data length > 1
    data = [df[df[group_col] == g][metric] for g in groups]
    
    if len(groups) == 2:
        stat, p = ttest_ind(*data)
        print(f"T-test between {groups[0]} and {groups[1]}: p = {p:.4f}")
    elif len(groups) > 2:
        stat, p = f_oneway(*data)
        print(f"ANOVA across groups in '{group_col}': p = {p:.4f}")
    else:
        print("Not enough groups to test.")

# Example usage:
# simple_stat_test(df, "Reward", "Algorithm")

In [153]:
# Sample dummy data
df = pd.DataFrame({
    'Algorithm': ['A', 'A', 'B', 'B', 'C', 'C'],
    'Reward': [100, 110, 90, 85, 105, 108]
})

simple_stat_test(df, "Reward", "Algorithm") #A p-value < 0.05 is typically considered statistically significant.

ANOVA across groups in 'Algorithm': p = 0.0472

In [ ]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
#  test is a post-hoc test used after an ANOVA to perform pairwise comparisons between the groups to determine which specific groups are significantly different 

# Apply Tukey's HSD test
tukey = pairwise_tukeyhsd(endog=df["Reward"], groups=df["Algorithm"], alpha=0.05)

# Print the results
print(tukey)

 Multiple Comparison of Means - Tukey HSD, FWER=0.05
=====================================================
group1 group2 meandiff p-adj   lower    upper  reject
-----------------------------------------------------
     A      B    -17.5  0.068 -37.2478  2.2478  False
     A      C      1.5 0.9469 -18.2478 21.2478  False
     B      C     19.0 0.0552  -0.7478 38.7478  False
-----------------------------------------------------

In [151]:
#df2 = data_exp_episode_effect[(data_exp_episode_effect['Algorithm']=='PPO')&((data_exp_episode_effect['Area']=='Area2 (Mosheer Ismail)'))]
for column in numeric_target_columns :
    simple_stat_test(data_exp_episode_effect, column, "Reward")

c:\Users\LapStore\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\stats\_stats_py.py:112: RuntimeWarning: The input array could not be properly checked for nan values. nan values will be ignored.
  warnings.warn("The input array could not be properly "

TypeError: can only concatenate str (not "float") to str

This mean according 2 algorithms , 2 areas  : Episodes not have significant affect (p>alpha =.05) in waiting time term

In [ ]:
for column in numeric_target_columns :
    simple_stat_test(data_exp_episode_effect, column, "Episodes")

In [116]:
import pandas as pd
from scipy.stats import f_oneway, ttest_ind
from statsmodels.stats.multicomp import pairwise_tukeyhsd

def run_statistical_tests(df, metric, group_col):
    unique_groups = df[group_col].unique()

    print(f"\n--- Statistical Test for: {metric} grouped by {group_col} ---")

    if len(unique_groups) == 2:
        # Two groups → use t-test
        group1, group2 = unique_groups
        data1 = df[df[group_col] == group1][metric]
        data2 = df[df[group_col] == group2][metric]
        stat, pval = ttest_ind(data1, data2, equal_var=False)
        print(f"t-test between {group1} and {group2}: p-value = {pval:.4f}")
    elif len(unique_groups) > 2:
        # More than two groups → use ANOVA
        groups = [df[df[group_col] == g][metric] for g in unique_groups]
        stat, pval = f_oneway(*groups)
        print(f"ANOVA across {group_col} groups: p-value = {pval:.4f}")

        if pval < 0.05:
            print("Significant difference detected — running Tukey HSD test:")
            tukey = pairwise_tukeyhsd(endog=df[metric], groups=df[group_col], alpha=0.05)
            print(tukey)
        else:
            print("No significant differences found.")
    else:
        print("Not enough groups for comparison.")

# 🔧 Usage example:
# Replace `your_df` with your DataFrame
# Run on metric "Reward", grouped by "Algorithm"

run_statistical_tests(data_exp_episode_effect, metric="Reward", group_col="Algorithm")

--- Statistical Test for: Reward grouped by Algorithm ---

c:\Users\LapStore\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\stats\_stats_py.py:112: RuntimeWarning: The input array could not be properly checked for nan values. nan values will be ignored.
  warnings.warn("The input array could not be properly "

TypeError: unsupported operand type(s) for /: 'str' and 'int'